version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 14
      java: openjdk8

  pre_build:
    commands:
      - echo "[Status] pre build started at `date`"
      - echo Current directory is `pwd`
      - echo STAGE $STAGE
      - echo DIST_BUCKET $DIST_BUCKET
      - echo FUNCTION_NAME $FUNCTION_NAME
      - echo WWW_BUCKET_NAME $WWW_BUCKET_NAME
      - echo CLOUDFRONT_DIST_ID $CLOUDFRONT_DIST_ID

      # Install software for API build
      - echo Installing sbt
      - aws s3 cp s3://$DIST_BUCKET/pokerdot/$STAGE/sbt.zip .
      - unzip sbt.zip

      # Install software for frontend build
      - cd frontend
      - yarn install
      - cd ..

      - echo "[STATUS] pre build step finished"

  build:
    commands:
      - echo "[Status] Build started at `date`"

      # test and package API
      - sbt/bin/sbt -no-colors test "project lambda" universal:packageBin
      # frontend
      - cd frontend
      - yarn test
      - yarn build
      - cd ..

      - echo "[STATUS] Build finished"

      - echo "[STATUS] Deploy started at `date`"

      - echo Deploying API to $FUNCTION_NAME
      - export DIST_KEY=pokerdot/$STAGE/pokerdot-lambda.zip
      - aws s3 cp lambda/target/universal/pokerdot-lambda.zip s3://$DIST_BUCKET/$DIST_KEY
      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $DIST_BUCKET --s3-key $DIST_KEY

      - echo Uploading static site to $WWW_BUCKET_NAME
      - cd frontend/dist
      - aws s3 sync . s3://$WWW_BUCKET_NAME
      - cd ../..
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths "/*"

      - echo "[STATUS] Deploy finished at `date`"

artifacts:
  files:
    - lambda/target/universal/pokerdot-lambda.zip
    - frontend/dist/**/*
