name: Poker Dot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up frontend toolchain
      uses: actions/setup-node@v2.1.5
      with:
        node-version: 12.x
    - name: Install toolchain dependencies
      run: npm install -g create-elm-app@5.22.0
      working-directory: frontend
    - name: Install project dependencies
      run: npm install
      working-directory: frontend
    - name: Test frontend
      run: elm-app test
      working-directory: frontend
    - name: build frontend
      run: elm-app build
      working-directory: frontend
