name: Poker Dot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'corretto'
        cache: 'sbt'
    - name: Run tests
      run: sbt test lambda/universal:packageBin

  test-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up frontend toolchain
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20.x
    - name: Install project dependencies
      run: npm install
      working-directory: frontend
    - name: Test frontend
      run: npm run test
      working-directory: frontend
    - name: build frontend
      run: npm run build
      working-directory: frontend
